name: Build, Deploy, and Accept

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/alpha-build.yml@master

  call-deploy:
    uses: trevorism/actions-workflows/.github/workflows/alpha-deploy.yml@master
    needs: call-build
    with:
      gcp_project: 'trevorism-testing'
      gcp_project_id: '729203316942'
      version: '0-2-0'

  call-accept:
    uses: trevorism/actions-workflows/.github/workflows/alpha-accept.yml@master
    with:
      INJECT_SECRETS: |
        Add-Content -Path .\build\staged-app\WEB-INF\classes\secrets.properties -Value 'clientId=${{ secrets.CLIENT_ID }}'
        Add-Content -Path .\build\staged-app\WEB-INF\classes\secrets.properties -Value 'clientSecret=${{ secrets.CLIENT_SECRET }}'
        Add-Content -Path .\build\staged-app\WEB-INF\classes\secrets.properties -Value 'signingKey=${{ secrets.SIGNING_KEY }}'


