name: Build, Deploy, and Accept

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/alpha-build.yml@master

  call-deploy:
    uses: trevorism/actions-workflows/.github/workflows/alpha-deploy.yml@master
    with:
      gcp_project: 'trevorism-testing'
      gcp_project_id: '729203316942'
      version: '0-2-0'

  call-accept:
    uses: trevorism/actions-workflows/.github/workflows/alpha-accept.yml@master
    with:
      classpath_secrets: ${{ toJSON(secrets) }}

