name: Build, Deploy, and Accept

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  call-build:
    uses: trevorism/actions-workflows/.github/workflows/alpha-build.yml@master

  call-deploy:
    uses: trevorism/actions-workflows/.github/workflows/alpha-deploy.yml@master
    needs: [call-build, call-accept-before]
    with:
      gcp_project: 'trevorism-testing'
      gcp_project_id: '729203316942'
      version: '0-2-0'
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      TOKEN: ${{ secrets.TOKEN }}

  call-accept-before:
    uses: trevorism/actions-workflows/.github/workflows/alpha-accept.yml@master
    secrets:
      TOKEN: ${{ secrets.TOKEN }}

  call-accept-after:
    uses: trevorism/actions-workflows/.github/workflows/alpha-accept.yml@master
    needs: call-deploy
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
