name: Build, Deploy, and Accept

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:


  call-accept:
    uses: trevorism/actions-workflows/.github/workflows/alpha-accept.yml@master
    secrets:
      SECRETS_CONTEXT: ${{ toJSON(secrets) }}

